---
name: Packer build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/xnat-web
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Packer install
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get -q update && sudo apt-get -yq install packer

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Artifacts
        run: |
          # run make instructions if file exists
          [[ -f Makefile ]] && make
          if packer validate "./"; then
            packer build -color=false -on-error=abort -only=docker.xnat-web "./"
          done
        env:
          PACKER_LOG: 1

      # Push docker image produced by packer with tags
      - name: Push docker image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: localhost:32000/xnat-web:ci
          dst: |
            ${{ steps.meta.outputs.tags }}
